# Generated by Django 5.1.1 on 2024-11-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='total_tokens',
        ),
    ]
