# Generated by Django 5.1.1 on 2024-11-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_chat_session_id_remove_chat_total_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
