# Generated by Django 5.1.1 on 2024-11-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_conversation',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.conversation'),
            preserve_default=False,
        ),
    ]
